WebAppProject/WebAppProject/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", accounts_views.login_views, name="home"),
    path("", include("django.contrib.auth.urls")),
    path("tu_talk/", include("tu_talk.urls")),
    path("tu_party/", include("tu_party.urls")),
    path("user/", include(("user_edit.urls"))),
    path("tu_alert/", include("tu_alert.urls")),
    path('tu_review/', include(('tu_review.urls'))),  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WebAppProject/tu_alert/urls.py
from django.urls import path
from . import views

app_name = "tu_alert"

urlpatterns = [
    path("", views.alert_list, name="alert_list"),
]

WebAppProject/tu_party/urls.py
from django.urls import path
from . import views

app_name = "tu_party"

urlpatterns = [
    path("", views.party_list, name="party_list"),
    path("create/", views.create_party, name="create_party"),
    path("<int:party_id>/interest/", views.interest_party, name="interest_party"),
    path(
        "party/<int:party_id>/interested-users/",
        views.interested_users_view,
        name="interested_users",
    ),
]

WebAppProject/tu_review/urls.py
from django.urls import path
from .views import *

app_name = "tu_review"

urlpatterns = [
    path("", tu_review, name="tu_review"),
    path("dorm/", DormListView.as_view(), name="dorm_list"),
    path("dorm/<int:dorm_id>/", DormDetailView.as_view(), name="dorm_detail"),
    path(
        "dorm/<int:dorm_id>/review/",
        DormReviewCreateView.as_view(),
        name="review_create",
    ),
    path(
        "review/<int:review_id>/delete/",
        ReviewDeleteView.as_view(),
        name="review_delete",
    ),
    path("dorm_create/", DormCreateView.as_view(), name="dorm_create_form"),
    path("study/", study, name="study"),
    path("faculty/<int:faculty_id>/", faculty_view, name="faculty"),
    path("faculty/<int:faculty_id>/add-review/", add_review_view, name="add_review"),
    path("review/<int:review_id>/delete/", delete_review_view, name="delete_review"),
    path("restaurant/", restaurant_list, name="restaurant_list"),
    path(
        "restaurant/<int:restaurant_id>/", restaurant_detail, name="restaurant_detail"
    ),
    path("restaurant/<int:restaurant_id>/review/", post_review, name="post_review"),
]

WebAppProject/tu_talk/urls.py
from django.urls import path
from . import views


app_name = "tu_talk"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("post/new/", views.create_post, name="create_post"),
    path("post/<int:post_id>/like/", views.like_post, name="like_post"),
    path("post/<int:post_id>/comment/", views.add_comment, name="add_comment"),
    path("post/<int:post_id>/comments/",views.view_all_comments,name="view_all_comments",
    ),
]

WebAppProject/user_edit/urls.py
from django.urls import path
from . import views

app_name = "user_edit"
 
urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('profile/edit/', views.profile_edit, name='profile_edit'),
]

WebAppProject/tu_review/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import View


# Models
class Dormitory(models.Model):
    name = models.CharField(max_length=255)
    location = models.TextField()
    image = models.ImageField(
        upload_to="dorms/images/",
        blank=True,
        null=True,
    )
    description = models.TextField()
    average_rating = models.FloatField(default=0.0)

    def __str__(self):
        return self.name


class DormReview(models.Model):
    dormitory = models.ForeignKey(
        Dormitory, on_delete=models.CASCADE, related_name="reviews"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    content = models.TextField()
    anonymous = models.BooleanField(default=False)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


# study
class Faculty(models.Model):
    name_th = models.CharField(max_length=255)
    name_en = models.CharField(max_length=255)
    description = models.TextField()
    established_date = models.DateField()
    color = models.CharField(max_length=7)  # Hex color code
    logo = models.ImageField(upload_to="faculty_logos/")

    def __str__(self):
        return self.name_en


class Course(models.Model):
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=255)
    faculty = models.ForeignKey(
        Faculty, on_delete=models.CASCADE, related_name="courses"
    )

    def __str__(self):
        return f"{self.code} - {self.name}"


class StudyReview(models.Model):
    COURSE_TYPES = [
        ("core", "วิชาเฉพาะ"),
        ("gen_ed", "วิชาศึกษาทั่วไป"),
        ("elective", "วิชาเลือกเสรี"),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="reviews")
    instructor = models.CharField(max_length=255)
    semester = models.IntegerField(
        choices=[(i, i) for i in range(1, 3)]
    )  # Rating for the restaurant (1-5)
    details = models.TextField()
    course_type = models.CharField(max_length=10, choices=COURSE_TYPES)
    interest = models.IntegerField(
        choices=[(i, i) for i in range(1, 6)]
    )  # Rating for the restaurant (1-5)
    practical_use = models.IntegerField(
        choices=[(i, i) for i in range(1, 6)]
    )  # Rating for the restaurant (1-5)
    future_use = models.IntegerField(
        choices=[(i, i) for i in range(1, 6)]
    )  # Rating for the restaurant (1-5)
    instructor_rating = models.IntegerField(
        choices=[(i, i) for i in range(1, 6)]
    )  # Rating for the restaurant (1-5)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.course.code} by {self.user.username}"


# resturant
class Restaurant(models.Model):
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    image = models.ImageField(upload_to="reviews/", null=True, blank=True)
    # Add more fields like description, etc. if needed

    def __str__(self):
        return self.name


class MenuItem(models.Model):
    restaurant = models.ForeignKey(
        Restaurant, related_name="menu_items", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name


class RestaurantReview(models.Model):
    restaurant = models.ForeignKey(
        Restaurant, related_name="reviews", on_delete=models.CASCADE
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review_text = models.TextField()
    rating = models.IntegerField(
        choices=[(i, i) for i in range(1, 6)]
    )  # Rating for the restaurant (1-5)
    cleanliness_rating = models.IntegerField(
        choices=[(i, i) for i in range(1, 6)]
    )  # Cleanliness rating (1-5)
    menu_rating = models.IntegerField(
        null=True, blank=True, choices=[(i, i) for i in range(1, 6)]
    )  # Rating for menu item (1-5)
    image = models.ImageField(upload_to="reviews/", null=True, blank=True)
    posted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Review by {self.user} for {self.restaurant}"

WebAppProject/tu_review/forms.py
from django import forms
from .models import *

class DormitoryCreateForm(forms.ModelForm):
    class Meta:
        model = Dormitory
        fields = ['name', 'location', 'image', 'description']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter dorm name'}),
            'location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter location'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'description': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter description'}),
        }

class DormReviewForm(forms.ModelForm):
    class Meta:
        model = DormReview
        fields = ['title', 'content', 'rating', 'anonymous']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter review title'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write your review here'}),
            'rating': forms.Select(attrs={'class': 'form-control'}, choices=[(i, i) for i in range(1, 6)]),
            'anonymous': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

#study
    
class StudyReviewForm(forms.ModelForm):
    class Meta:
        model = StudyReview
        fields = ['course', 'instructor', 'semester', 'details', 'course_type', 'interest', 'practical_use', 'future_use', 'instructor_rating']

#resturant

class ResturantReviewForm(forms.ModelForm):
    class Meta:
        model = RestaurantReview
        fields = ['restaurant','review_text', 'rating', 'cleanliness_rating', 'menu_rating', 'image']
        widgets = {
            'review_text': forms.Textarea(attrs={'rows': 5}),
        }

WebAppProject/tu_review/views.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.views import View
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import path
from django import forms
from django.contrib import admin
from django.db.models import Avg


def tu_review(request):
    return render(request, "gateway.html")


# dorm
class DormListView(View):
    def get(self, request):
        dorms = Dormitory.objects.all().order_by("-average_rating")
        return render(request, "dorm_list.html", {"dorms": dorms})


class DormDetailView(View):
    def get(self, request, dorm_id):
        dorm = get_object_or_404(Dormitory, id=dorm_id)
        reviews = dorm.reviews.all()
        return render(request, "dorm_detail.html", {"dorm": dorm, "reviews": reviews})


class DormReviewCreateView(View):
    def post(self, request, dorm_id):
        dorm = get_object_or_404(Dormitory, id=dorm_id)
        title = request.POST["title"]
        content = request.POST["content"]
        rating = int(request.POST["rating"])
        anonymous = "anonymous" in request.POST
        review = DormReview.objects.create(
            dormitory=dorm,
            user=request.user,
            title=title,
            content=content,
            rating=rating,
            anonymous=anonymous,
        )

        # Update average rating
        reviews = dorm.reviews.all()
        dorm.average_rating = sum(r.rating for r in reviews) / len(reviews)
        dorm.save()

        return redirect("tu_review:dorm_detail", dorm_id=dorm.id)


class ReviewDeleteView(View):
    def post(self, request, review_id):
        review = get_object_or_404(DormReview, id=review_id, user=request.user)
        review.delete()

        # Update average rating
        dorm = review.dormitory
        reviews = dorm.reviews.all()
        dorm.average_rating = (
            sum(r.rating for r in reviews) / len(reviews) if reviews else 0.0
        )
        dorm.save()

        return redirect("tu_review:dorm_detail", dorm_id=dorm.id)


class DormCreateView(View):
    def get(self, request):
        form = DormitoryCreateForm()
        return render(request, "dorm_create_form.html", {"form": form})

    def post(self, request):
        form = DormitoryCreateForm(request.POST, request.FILES)
        if form.is_valid():
            dorm = form.save()
            return redirect("tu_review:dorm_list")  # Redirect ไปยังหน้ารายการหอพัก
        return render(request, "dorm_create_form.html", {"form": form})


# study


def study(request):
    faculties = Faculty.objects.all()
    top_courses = Course.objects.annotate(avg_rating=Avg("reviews__interest")).order_by(
        "-avg_rating"
    )[:3]
    return render(
        request, "study.html", {"faculties": faculties, "top_courses": top_courses}
    )


def faculty_view(request, faculty_id):
    faculty = get_object_or_404(Faculty, id=faculty_id)
    courses = faculty.courses.all()
    return render(
        request, "study_faculty.html", {"faculty": faculty, "courses": courses}
    )


@login_required
def add_review_view(request, faculty_id):
    faculty = get_object_or_404(Faculty, id=faculty_id)
    if request.method == "POST":
        form = StudyReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            review.save()
            return redirect("tu_review:faculty", faculty_id=faculty.id)
    else:
        form = StudyReviewForm()
    return render(request, "study_add_review.html", {"form": form, "faculty": faculty})


@login_required
def delete_review_view(request, review_id):
    review = get_object_or_404(StudyReview, id=review_id, user=request.user)
    review.delete()
    return JsonResponse({"success": True})


# resturant
# View to list restaurants
def restaurant_list(request):
    restaurants = Restaurant.objects.all()
    # Get top 3 restaurants with the highest average rating
    top_restaurants = Restaurant.objects.annotate(
        avg_rating=models.Avg("reviews__rating")
    ).order_by("-avg_rating")[:3]
    return render(
        request,
        "restaurant_list.html",
        {"restaurants": restaurants, "top_restaurants": top_restaurants},
    )


# View to see restaurant details and reviews
def restaurant_detail(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, id=restaurant_id)
    reviews = restaurant.reviews.all()
    return render(
        request,
        "restaurant_detail.html",
        {"restaurant": restaurant, "reviews": reviews},
    )


# View to post a review
def post_review(request, restaurant_id):
    restaurant = get_object_or_404(Restaurant, id=restaurant_id)

    if request.method == "POST":
        form = ResturantReviewForm(request.POST, request.FILES)
        if form.is_valid():
            review = form.save(commit=False)
            review.restaurant = restaurant
            review.user = request.user
            review.save()
            return redirect("tu_review:restaurant_detail", restaurant_id=restaurant.id)
    else:
        form = ResturantReviewForm()

    return render(
        request, "restaurant_post_review.html", {"form": form, "restaurant": restaurant}
    )

WebAppProject/tu_review/templates/dorm_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style_review.css' %}">
    <title>Dorm detail</title>
</head>
<body>
    <!-- Navigation Bar with Post Form in Center -->
    <nav class="navbar">
        <a href="{% url 'user_home' %}" class="logo">TUTALK</a>

        <div class="nav-links">
            <a href="{% url 'user_edit:profile' %}">My account</a>
            <a href="{% url 'home' %}">Log Out</a>
        </div>
    </nav>

    <!-- Left Menu with Search Bar -->

    <div class="left-menu">
        <a href="{% url 'tu_talk:post_list' %}"
            class="{% if request.resolver_match.url_name == 'post_list' %}active{% endif %}">
            TU Talk
        </a>
        <a href="{% url 'tu_alert:alert_list' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
            TU Alert
        </a>
        <a href="{% url 'tu_review:tu_review' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
            TU Review
        </a>
        <a href="{% url 'tu_party:party_list' %}" class="{% if request.resolver_match.url_name == 'party_list' %}active{% endif %}">
            TU Party
        </a>
        <a href="{% url 'about' %}" class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">
            About Us
        </a>
    </div>

     <!-- Footer Section -->
     <footer class="footer">
        <p>&copy; 2024 TUTALK. All rights reserved.</p>
    </footer>

    <div class="maindorm_details">
            <h1>{{ dorm.name }}</h1>
        {% if dorm.image %}
            <img src="{{ dorm.image.url }}" alt="Dorm image" class="dorm-image">
            {% else %}
            <p>No image available</p>
        {% endif %}
        <p>{{ dorm.description }}</p>
        <p>Location: {{ dorm.location }}</p>
        <p>Average Rating: {{ dorm.average_rating }}</p>

        <h2>Reviews</h2>
        {% for review in reviews %}
        <div>
            <h3>{{ review.title }}</h3>
            <p>{{ review.content }}</p>
            <p>Rating: {{ review.rating }}</p>
            <p>By: {% if not review.anonymous %}{{ review.user.username }}{% else %}Anonymous{% endif %}</p>
            <p>Date: {{ review.created_at }}</p>
            {% if review.user == request.user %}
                <form method="post" action="{% url 'tu_review:review_delete' review.id %}">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    
    <div class="maindorm_review">
        <h2>Add a Review</h2>
        <form method="post" enctype="multipart/form-data" action="{% url 'tu_review:review_create' dorm.id %}">
        {% csrf_token %}
            <input type="text" name="title" placeholder="Title" required>
            <input type="describe" name="content" placeholder="Review Content" required>
            <input type="describe" name="recommendation" placeholder="Recommendation" required>
            <input type="number" name="rating" min="1" max="5"placeholder="Rate 1-5" required>
            <label><input type="checkbox" name="anonymous"> Post Anonymously</label>
            <button type="submit">Submit</button>
    </form>

</div>
    <div class="goback">
        <h2><a href="{% url 'tu_review:dorm_list' %}">Go Back</a></h2>
    </div>

</body>
</html>

WebAppProject/tu_review/templates/gateway.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style_review.css' %}">
    <title>TU REVIEW</title>
</head>
<body>
    <nav class="navbar">
        <a href="{% url 'user_home' %}" class="logo">TUTALK</a>
        <div class="nav-links">
            <a href="{% url 'user_edit:profile' %}">My account</a>
            <a href="{% url 'home' %}">Log Out</a>
        </div>
    </nav>

    <div class="container">
        <div class="left-menu">
            <a href="{% url 'tu_talk:post_list' %}"
                class="{% if request.resolver_match.url_name == 'post_list' %}active{% endif %}">
                TU Talk
            </a>
            <a href="{% url 'tu_alert:alert_list' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                TU Alert
            </a>
            <a href="{% url 'tu_review:tu_review' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                TU Review
            </a>
            <a href="{% url 'tu_party:party_list' %}" class="{% if request.resolver_match.url_name == 'party_list' %}active{% endif %}">
                TU Party
            </a>
            <a href="{% url 'about' %}" class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">
                About Us
            </a>
        </div>
        
        <header class="header">
            TU Review
        </header>
        
        <div class="maingate">
            <a href="{% url 'tu_review:study' %}">
                <img src="{% static 'images/book-pile-of-must-read-books-scaled1.jpeg' %}" alt="Course Icon">
                <span>Course</span>
            </a>
            <a href="{% url 'tu_review:dorm_list' %}">
                <img src="{% static 'images/dorm1.jpg' %}" alt="Dorm Icon">
                <span>Dorm</span>
            </a>
            <a href="{% url 'tu_review:restaurant_list' %}">
                <img src="{% static 'images/Food1.png' %}" alt="Restaurant Icon">
                <span>Restaurant</span>
            </a>
        </div>
    </div>


     <!-- Footer Section -->
     <footer class="footer">
        <p>&copy; 2024 TUTALK. All rights reserved.</p>
    </footer>
    


</body>
</html>

WebAppProject/tu_review/templates/restaurant_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css\style_restaurant.css' %}">
    <title>Resturant details</title>
</head>
<body>
    <nav class="navbar">
        <a href="{% url 'user_home' %}" class="logo">TUTALK</a>
        <div class="nav-links">
            <a href="{% url 'user_edit:profile' %}">My account</a>
            <a href="{% url 'home' %}">Log Out</a>
        </div>
    </nav>
    
    <div class="container">
        <div class="left-menu">
            <a href="{% url 'tu_talk:post_list' %}"
                class="{% if request.resolver_match.url_name == 'post_list' %}active{% endif %}">
                TU Talk
            </a>
            <a href="{% url 'tu_alert:alert_list' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                TU Alert
            </a>
            <a href="{% url 'tu_review:tu_review' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                TU Review
            </a>
            <a href="{% url 'tu_party:party_list' %}" class="{% if request.resolver_match.url_name == 'party_list' %}active{% endif %}">
                TU Party
            </a>
            <a href="{% url 'about' %}" class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">
                About Us
            </a>
        </div>
        
        
        <div class="headerReview">
            <h3>Reviews</h3>
        </div>
        
        {% for review in reviews %}
        <div class="ReviewRating">
            <p1>{{ review.user }}</p1>
            <p>Rating: {{ review.rating }}/5</p>
            <p>Menu Rating: {{ review.menu_rating }}/5</p>
            <p>Cleanliness Rating: {{ review.cleanliness_rating }}/5</p>
            <p>Comment: {{ review.review_text }}</p>
            <p>Date:   {{ review.posted_at }}</p>
        </div>

    {% endfor %}
        <div class="links">
            <a href="{% url 'tu_review:post_review' restaurant.id %}">Post a Review</a>
            <a href="{% url 'tu_review:restaurant_list' %}">Go back</a>
        </div>
    </div>    

    <footer class="footer">
        <p>&copy; 2024 TUTALK. All rights reserved.</p>
    </footer>

</body>
</html>

WebAppProject/tu_review/templates/restaurant_post_review.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css\style_restaurant.css' %}">
    <title>Post</title>
</head>
<body>
    <nav class="navbar">
        <a href="{% url 'user_home' %}" class="logo">TUTALK</a>
        <div class="nav-links">
            <a href="{% url 'user_edit:profile' %}">My account</a>
            <a href="{% url 'home' %}">Log Out</a>
        </div>
    </nav>

    <div class="container">
        <div class="left-menu">
            <a href="{% url 'tu_talk:post_list' %}"
                class="{% if request.resolver_match.url_name == 'post_list' %}active{% endif %}">
                TU Talk
            </a>
            <a href="{% url 'tu_alert:alert_list' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                TU Alert
            </a>
            <a href="{% url 'tu_review:tu_review' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                TU Review
            </a>
            <a href="{% url 'tu_party:party_list' %}" class="{% if request.resolver_match.url_name == 'party_list' %}active{% endif %}">
                TU Party
            </a>
            <a href="{% url 'about' %}" class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">
                About Us
            </a>
        </div>


        <div class="review-container">
            <h2>Post a Review for {{ restaurant.name }}</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Submit Review</button>
            </form>
            <a href="{% url 'tu_review:restaurant_list' %}">Go back</a>
        </div>
    </div>    

    <footer class="footer">
        <p>&copy; 2024 TUTALK. All rights reserved.</p>
    </footer>

</body>
</html>

WebAppProject/tu_review/templates/study_faculty.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css\style_study.css' %}">
    <title>Study Faculty</title>
</head>
<body>
    <nav class="navbar">
        <a href="{% url 'user_home' %}" class="logo">TUTALK</a>
        <div class="nav-links">
            <a href="{% url 'user_edit:profile' %}">My account</a>
            <a href="{% url 'home' %}">Log Out</a>
        </div>
    </nav>

    <div class="container">
        <div class="left-menu">
            <a href="{% url 'tu_talk:post_list' %}"
                class="{% if request.resolver_match.url_name == 'post_list' %}active{% endif %}">
                TU Talk
            </a>
            <a href="{% url 'tu_alert:alert_list' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                TU Alert
            </a>
            <a href="{% url 'tu_review:tu_review' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                TU Review
            </a>
            <a href="{% url 'tu_party:party_list' %}" class="{% if request.resolver_match.url_name == 'party_list' %}active{% endif %}">
                TU Party
            </a>
            <a href="{% url 'about' %}" class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">
                About Us
            </a>
        </div>

        <div class="NameFaculty">
            <h1>{{ faculty.name_en }}</h1>
            <p>{{ faculty.description }}</p>
        </div>

        <div class="CoursesName">
            <h2>Courses</h2>
            <ul>
                <div class="CoursesContainer">
                    {% for course in courses %}
                    <div class="CourseBox">
                        <h3>{{ course.code }} - {{ course.name }}</h3>
                        {% if course.reviews.all %}
                            <h4>Reviews</h4>
                            <ul class="ReviewList">
                                {% for review in course.reviews.all %}
                                <li>
                                    <strong>By {{ review.user.username }}</strong> ({{ review.created_at|date:"d M Y" }})<br>
                                    <strong>Instructor:</strong> {{ review.instructor }}<br>
                                    <strong>Semester:</strong> {{ review.semester }}<br>
                                    <strong>Course Type:</strong> {{ review.get_course_type_display }}<br>
                                    <strong>Interest:</strong> {{ review.interest }}<br>
                                    <strong>Practical Use:</strong> {{ review.practical_use }}<br>
                                    <strong>Future Use:</strong> {{ review.future_use }}<br>
                                    <strong>Instructor Rating:</strong> {{ review.instructor_rating }}<br>
                                    <p>Comment: {{ review.details }}</p>
                                </li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <p>No reviews for this course yet.</p>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
                
            </ul>
            <div class="button-group">
                <a href="{% url 'tu_review:add_review' faculty.id %}" class="button">Add Review</a>
                <a href="{% url 'tu_review:study' %}" class="button back-button">Go Back</a>
            </div>
        </div>
    </div>

    <footer class="footer">
        <p>&copy; 2024 TUTALK. All rights reserved.</p>
    </footer>

</body>
</html>